### ISSUE TITLE
Initializer required in Rails

### ISSUE THREAD

**Issue by russellbrown** [carnesmedia/shortcodes#1]
In Rails, `shortcodes/all.rb` (which references the youtube.rb and wufoo.rb shortcodes) doesn't get loaded by default, so you have to create an initializer in your application called something like `config/initializers/shortcodes.rb` containing:

```
require 'shortcodes/wufoo'
require 'shortcodes/youtube'
```

If you create your own shortcodes (e.g. `lib/shortcodes/custom.rb` - you can use youtube.rb as a starting point for developing your own shortcode), remember to reference it in the initializer:

```
require 'shortcodes/custom'
```

Hope that helps someone else.  Great gem by the way, thanks!

**Comment by amiel** [comment]
@russellbrown Thanks for bringing this up. Ultimately, I think this is a documentation issue.

I'll add something to the `README` to clear this up.

**Comment by amiel** [comment]
@russellbrown I've amended the [README](https://github.com/carnesmedia/shortcodes/blob/master/README.md). Let me know if you have any other suggestions :smile:
