### ISSUE TITLE
Support for block/container tags

### ISSUE THREAD

**Issue by russellbrown** [carnesmedia/shortcodes#2]
Are there any plans to support block/container shortcodes which can contain other shortcodes?  For example:

```
[timeline title="My true love gave to me..."]
  [event date="25/12/2013" description="A Partridge in a Pear Tree"]
  [event date="26/12/2013" description="2 Turtle Doves"]
  [event date="27/12/2013" description="3 French Hens"]
  [event date="28/12/2013" description="4 Calling Birds"]
  [event date="29/12/2013" description="5 Golden Rings"]
[/timeline]
```

Just a suggestion, I think it would be really useful.

**Comment by amiel** [comment]
That looks like a great feature!

I'm not actively developing shortcodes at the moment, so I won't be writing this in the very near future, but I might take a stab at it next time I dive in...

If you feel like giving it a shot, I look forward to your pull-request :smile:

**Comment by kernow** [comment]
@russellbrown FYI my shortcode gem supports block tags, take a look at https://github.com/kernow/shortcode

**Comment by russellbrown** [comment]
@kernow Great, thanks!
